#!/bin/sh

# sshd_config(5):
# ...
# If no arguments are specified then the username of the target user is used.
# The program should produce on standard output zero or more lines of
# authorized_keys output (see AUTHORIZED_KEYS in sshd(8)).
username="${1}"

# Does this username exist?  If not, quit.
id -u "${username}" >/dev/null || exit $?

path="/etc/ssh/authorized_keys/${username}"
if [[ -d "${path}" ]]; then
    # If authorized keys are provided in a directory, concatenate them.
    # Assume all .pub files in the directory are authorized login keys.
    find "${path}" -maxdepth 1 -type f -name "*.pub" | xargs cat
elif [[ -f "${path}" ]]; then
    # If authorized keys are provided in a single file, just forward it.
    cat "${path}";
fi
